name: Lint code & compile test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: kakushindev/workflows/.github/workflows/lint-and-compile-test.yml@main
    secrets: inherit
